import type { HexCell } from './HexGrid.ts';
import type { WallBuilding, WallResolution } from './Wall.ts';
import type { PlacedBuilding } from './Building.ts';
import type { StructureDetectionResult } from './multistructureDetection.ts';
import type { HomogeneousResolvedEntity } from '../homogeneousValueResolution.ts';
import type { RequirementResolutionData } from '../progression/requirements.ts';
import type { DevelopmentVectorValue } from '../DevlopmentVector.ts';

export type SelectedHexPanelProps = {
    selectedHex: HexCell;
    selectedBuilding?: PlacedBuilding;
    selectedResolvedEntity?: HomogeneousResolvedEntity;
    selectedWallBuilding?: WallBuilding;
    selectedWallTopBuilding?: WallBuilding;
    panelVector?: DevelopmentVectorValue;
    structureCandidates: StructureDetectionResult[];
    builtStructureIds: ReadonlySet<string>;
    unlockedBuildingIds: ReadonlySet<string>;
    requirementResolutionData: RequirementResolutionData;
    isPartOfCompleteStructure: boolean;
    wallResolution: WallResolution;
    blocked: boolean;
    blockedReason: string;
    isLost: boolean;
    lostReason: string;
    emphasizeEditWallTopTower?: boolean;
    onBuildStructure: (structureId: string, coreCellKey: string) => void;
    onDemolish: () => void;
    onDemolishWallTop: () => void;
    onEditWallTopTower: () => void;
};
